In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [11]:
s1 = Series([1,2,3],index=['X','Y','Z'])
s1

X    1
Y    2
Z    3
dtype: int64

In [12]:
s2 = Series([4,5],index=['A','B'])
s2

A    4
B    5
dtype: int64

In [13]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [14]:
pd.concat([s1,s2], axis=1)

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
A  NaN  4.0
B  NaN  5.0

In [15]:
df1 = DataFrame(np.random.rand(4,3), columns=['X','Y','Z'])
df1

X         Y         Z
0  0.857845  0.940232  0.737617
1  0.454392  0.570534  0.110128
2  0.234883  0.421762  0.170431
3  0.119959  0.185266  0.978378

In [16]:
df2 = DataFrame(np.random.rand(4,3), columns=['X','Y','A'])
df2

X         Y         A
0  0.734980  0.429206  0.414436
1  0.196921  0.795107  0.830522
2  0.897019  0.375062  0.031869
3  0.095103  0.911014  0.795066

In [18]:
pd.concat([df1,df2])

X         Y         Z         A
0  0.857845  0.940232  0.737617       NaN
1  0.454392  0.570534  0.110128       NaN
2  0.234883  0.421762  0.170431       NaN
3  0.119959  0.185266  0.978378       NaN
0  0.734980  0.429206       NaN  0.414436
1  0.196921  0.795107       NaN  0.830522
2  0.897019  0.375062       NaN  0.031869
3  0.095103  0.911014       NaN  0.795066

# Combine

In [19]:
s1 = Series([2,np.nan, 4,np.nan], index = ['A','B','C','D'])
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [20]:
s2 = Series([1,2,3,4], index = ['A','B','C','D'])
s2

A    1
B    2
C    3
D    4
dtype: int64

In [21]:
s1.combine_first(s2)
# 用s2填充s1里的nan

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [25]:
df1 = DataFrame({
    'X':[1,np.nan,3,np.nan],
    'Y':[1,2,3,4],
    'Z':[np.nan, 1,2,3]
})
df1

X  Y    Z
0  1.0  1  NaN
1  NaN  2  1.0
2  3.0  3  2.0
3  NaN  4  3.0

In [26]:
df2 = DataFrame({
    'X':[1,1,3,np.nan],
    'Z':[1,1,2,np.nan]
})
df2

X    Z
0  1.0  1.0
1  1.0  1.0
2  3.0  2.0
3  NaN  NaN

In [27]:
df1.combine_first(df2)

X  Y    Z
0  1.0  1  1.0
1  1.0  2  1.0
2  3.0  3  2.0
3  NaN  4  3.0

In [28]:
df1

X  Y    Z
0  1.0  1  NaN
1  NaN  2  1.0
2  3.0  3  2.0
3  NaN  4  3.0