# 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
f = open('x.pkl', 'wb')
pickle.dump(x, f)

In [5]:
!ls

Array.ipynb                 x.pkl
Array的input output.ipynb   数组与矩阵运算.ipynb


In [6]:
f = open('x.pkl', 'rb')
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# numpy 提供的方法

In [7]:
np.save('one_array', x)

In [8]:
!ls

Array.ipynb                 x.pkl
Array的input output.ipynb   数组与矩阵运算.ipynb
one_array.npy


In [9]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.savez('two_array', a=x, b=y)
!ls

Array.ipynb                 two_array.npz
Array的input output.ipynb   x.pkl
one_array.npy               数组与矩阵运算.ipynb


In [12]:
c = np.load('two_array.npz')
c

In [16]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# https://docs.scipy.org/doc/